### ISSUE TITLE
[US-14-2](Merge with 14-3) As a User I want to comment on a picture [3]

### ISSUE THREAD

**Issue by CSman22** [halloweentown/SOEN341-W21-A7#29]
This will allow the user to be engaged with the post 

Specification 
- [x] Text entry must accept a maximum of 300 characters
- [x] Able to comment that can be viewed by others

### **Acceptance Criteria**
- [x] Posted image should have a designated text box to allow comments to be added to it
- [x] Comments should be added to database and linked to the corresponding post
- [x] Comments are permanently added below the post 
- [x] There can be multiple comments to a single post

**Comment by halloweentown** [comment]
Closed as issue is duplicate
